"""Assemble the English manuscript (Markdown + figures) into a single .docx.

Design choices, and why:

- **Pandoc first.** The manuscript sources are already Markdown with tables,
  images and emphasis. Pandoc converts all of that natively, honours a
  ``--reference-doc`` for journal styling, and needs no bespoke parser. A
  hand-rolled Markdown reader would silently drop table alignment or nested
  emphasis.
- **python-docx fallback.** Pandoc is not always installed. The fallback covers
  headings, paragraphs, bullet lists, tables and images — enough to inspect the
  document — and says plainly in the log that formatting is degraded, so a
  fallback build is never mistaken for the real one.
- **Figure paths are resolved, then verified.** A missing image is reported by
  name rather than silently skipped: a manuscript that builds while quietly
  dropping Figure 7 is worse than one that fails.
- **The numeric tables are carried into the document.** The figure export writes
  ``T*.csv`` next to the figures; `build_data_appendix` turns them into a
  Markdown appendix so the .docx contains the numbers behind the plots, not only
  the plots.
"""

from __future__ import annotations

import csv
import re
import shutil
import subprocess
import zipfile
from pathlib import Path

# Section files, in manuscript order. Explicit rather than globbed: the order of
# a manuscript is editorial, not alphabetical, and a new file must be placed
# deliberately. `09_appendix_data.md` is generated by `build_data_appendix`; it
# is listed here so it slots in automatically, and skipped when absent.
SECTION_ORDER = [
    "00_title_abstract.md",
    "01_introduction.md",
    "02_study_area_and_data.md",
    "03_methods.md",
    "04_results.md",
    "05_discussion.md",
    "06_conclusions.md",
    "07_appendix_alternatives.md",
    "08_references.md",
    "09_appendix_data.md",
]

IMG_RE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")

# Titles for the exported CSV tables, so the appendix reads as a document rather
# than as a directory listing. Unlisted files fall back to their stem.
TABLE_TITLES = {
    "T01_zones": "Zone definition, pixel counts and areas",
    "T02_temporal_coherence": "Temporal coherence by zone (phase linking)",
    "T03_multithreshold": "Usable fraction against the coherence threshold",
    "T04_zone_signature": "Multi-sensor signature of the zones",
    "T05_paired_test": "Paired mat-versus-grassland coherence test",
    "T06_predictors": "Failure predictors, with and without collinear terms",
    "T07_seasonal_amplitudes": "Seasonal amplitudes and empirical p-values",
    "T08_closure_phase": "Closure-phase bias and dispersion by zone",
    "T09_forcings": "Hydro-climatic forcings, raw and deseasonalised",
    "T10_hydrology_freeze": "Coherence response to freezing",
}


def collect_sections(paper_dir: str | Path,
                     order: list[str] | None = None) -> list[Path]:
    """Return the existing section files, in manuscript order.

    Missing files are skipped silently (a section may not be written yet), but
    `assemble_markdown` reports the list actually used so gaps are visible."""
    paper_dir = Path(paper_dir)
    return [paper_dir / n for n in (order or SECTION_ORDER)
            if (paper_dir / n).exists()]


def find_missing_images(md_text: str, base_dir: str | Path) -> list[str]:
    """Image references in `md_text` that do not resolve on disk."""
    base_dir = Path(base_dir)
    missing = []
    for _, src in IMG_RE.findall(md_text):
        if src.startswith(("http://", "https://")):
            continue
        if not (base_dir / src).exists():
            missing.append(src)
    return missing


def assemble_markdown(paper_dir: str | Path, out_md: str | Path,
                      title: str | None = None,
                      order: list[str] | None = None) -> dict:
    """Concatenate the section files into one Markdown document.

    Sections are separated by a blank line rather than a page break, leaving
    pagination to the Word template. Returns a report: files used, image
    references found, and any that do not resolve."""
    paper_dir, out_md = Path(paper_dir), Path(out_md)
    files = collect_sections(paper_dir, order)
    if not files:
        raise FileNotFoundError(f"no section file found in {paper_dir}")
    parts = []
    if title:
        parts.append(f"% {title}\n")
    for f in files:
        parts.append(f.read_text(encoding="utf-8").rstrip() + "\n")
    text = "\n\n".join(parts)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(text, encoding="utf-8")
    imgs = [s for _, s in IMG_RE.findall(text)]
    return {"files": [f.name for f in files], "n_sections": len(files),
            "images": imgs, "missing_images": find_missing_images(text, paper_dir),
            "chars": len(text), "out_md": out_md}


def csv_to_markdown(csv_path: str | Path, max_rows: int = 40) -> str:
    """Render a CSV as a Markdown pipe table.

    Long tables are truncated with an explicit note rather than silently: a
    reader must never be shown a partial table that looks complete. Pipe
    characters in cells are escaped, otherwise they would break the table."""
    csv_path = Path(csv_path)
    with csv_path.open(newline="", encoding="utf-8") as fh:
        rows = [r for r in csv.reader(fh) if any(c.strip() for c in r)]
    if not rows:
        return "_(empty table)_\n"
    ncol = max(len(r) for r in rows)
    rows = [r + [""] * (ncol - len(r)) for r in rows]
    head, body = rows[0], rows[1:]
    truncated = len(body) > max_rows
    shown = body[:max_rows]

    def fmt(cells):
        return "| " + " | ".join(c.replace("|", "\\|").strip()
                                 for c in cells) + " |"

    out = [fmt(head), "|" + "---|" * ncol]
    out += [fmt(r) for r in shown]
    if truncated:
        out.append("")
        out.append(f"_({len(body) - max_rows} further rows omitted; "
                   f"full table in `figures/{csv_path.name}`.)_")
    return "\n".join(out) + "\n"


def build_data_appendix(figures_dir: str | Path, out_md: str | Path,
                        heading: str = "## Appendix B. Numeric tables",
                        max_rows: int = 40) -> dict:
    """Turn the exported ``T*.csv`` files into a Markdown appendix.

    Written as a separate section file so the appendix is regenerated from the
    CSVs rather than hand-maintained: the numbers in the document then cannot
    drift from the numbers the notebook computed."""
    figures_dir, out_md = Path(figures_dir), Path(out_md)
    csvs = sorted(figures_dir.glob("T*.csv"))
    parts = [heading, "",
             "Tables exported by `notebooks/export_figures_en.ipynb`. Each is "
             "reproduced here and shipped as CSV alongside the figures.", ""]
    for c in csvs:
        title = TABLE_TITLES.get(c.stem, c.stem.replace("_", " "))
        label = c.stem.split("_")[0]
        parts += [f"### {label}. {title}", "",
                  csv_to_markdown(c, max_rows=max_rows), ""]
    if not csvs:
        parts += ["_No table has been exported yet; "
                  "run the figure-export notebook first._", ""]
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text("\n".join(parts), encoding="utf-8")
    return {"n_tables": len(csvs), "tables": [c.name for c in csvs],
            "out_md": out_md}


# Image types a figure export can plausibly emit, and their OPC content types.
_MEDIA_TYPES = {
    "png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg",
    "gif": "image/gif", "tif": "image/tiff", "tiff": "image/tiff",
    "bmp": "image/bmp", "svg": "image/svg+xml", "emf": "image/x-emf",
    "wmf": "image/x-wmf", "pdf": "application/pdf",
}


def repair_content_types(docx_path: str | Path) -> list[str]:
    """Declare every embedded media extension in ``[Content_Types].xml``.

    Works around a pandoc 3.1.x defect: images are written into ``word/media/``
    without the matching ``<Default Extension=.../>``, and the OPC package is
    then invalid — LibreOffice refuses the file outright with "source file could
    not be loaded", and other readers may drop the figures silently. Since a
    manuscript whose figures are the point must actually open, this runs on
    every build.

    Returns the extensions that had to be added (empty when nothing was wrong)."""
    docx_path = Path(docx_path)
    with zipfile.ZipFile(docx_path) as zin:
        items = {n: zin.read(n) for n in zin.namelist()}
    ct_name = "[Content_Types].xml"
    if ct_name not in items:
        return []
    ct = items[ct_name].decode("utf-8")
    exts = {Path(n).suffix.lstrip(".").lower()
            for n in items if n.startswith("word/media/")}
    added = []
    for ext in sorted(exts):
        mime = _MEDIA_TYPES.get(ext)
        if not mime or re.search(rf'Extension="{ext}"', ct, re.I):
            continue
        ct = ct.replace("</Types>",
                        f'<Default Extension="{ext}" ContentType="{mime}"/>'
                        "</Types>", 1)
        added.append(ext)
    if not added:
        return []
    items[ct_name] = ct.encode("utf-8")
    with zipfile.ZipFile(docx_path, "w", zipfile.ZIP_DEFLATED) as zout:
        for n, b in items.items():
            zout.writestr(n, b)
    return added


# Academic ("booktabs") table style: a rule above the header, a rule under it,
# a rule below the last row, and no vertical lines. Pandoc's own `Table` style
# carries no borders at all and zero vertical cell padding, which is why an
# unstyled table reads as text adrift on the page rather than as a table.
_TABLE_STYLE = '''<w:style w:default="1" w:styleId="Table" w:type="table">
<w:name w:val="Table"/><w:basedOn w:val="TableNormal"/><w:semiHidden/>
<w:unhideWhenUsed/><w:qFormat/>
<w:tblPr><w:tblInd w:type="dxa" w:w="0"/>
<w:tblBorders>
<w:top w:val="single" w:sz="12" w:space="0" w:color="000000"/>
<w:left w:val="none" w:sz="0" w:space="0" w:color="auto"/>
<w:bottom w:val="single" w:sz="12" w:space="0" w:color="000000"/>
<w:right w:val="none" w:sz="0" w:space="0" w:color="auto"/>
<w:insideH w:val="none" w:sz="0" w:space="0" w:color="auto"/>
<w:insideV w:val="none" w:sz="0" w:space="0" w:color="auto"/>
</w:tblBorders>
<w:tblCellMar><w:top w:type="dxa" w:w="70"/><w:left w:type="dxa" w:w="108"/>
<w:bottom w:type="dxa" w:w="70"/><w:right w:type="dxa" w:w="108"/></w:tblCellMar>
</w:tblPr>
<w:tblStylePr w:type="firstRow">
<w:rPr><w:b/></w:rPr>
<w:tblPr><w:jc w:val="left"/><w:tblInd w:type="dxa" w:w="0"/></w:tblPr>
<w:trPr><w:jc w:val="left"/></w:trPr>
<w:tcPr><w:vAlign w:val="bottom"/>
<w:tcBorders><w:bottom w:val="single" w:sz="8" w:space="0" w:color="000000"/></w:tcBorders>
</w:tcPr>
</w:tblStylePr>
</w:style>'''


def polish_tables(docx_path: str | Path, full_width: bool = True) -> int:
    """Make the tables in a built .docx read as tables.

    The border and padding work lives in the reference document's ``Table``
    style, but two things can only be fixed on the output, because pandoc writes
    them into each table's own ``tblPr`` where they override the style:

    - **width**: pandoc emits ``tblW type="auto"``, so each table is sized to its
      content and neighbouring tables end up different widths. Setting 100 %
      makes them line up with the text column and with each other.
    - **header repeat**: a table split across a page break must repeat its header
      row, otherwise the continuation is a block of unlabelled numbers.

    Returns the number of tables adjusted."""
    docx_path = Path(docx_path)
    with zipfile.ZipFile(docx_path) as zin:
        items = {n: zin.read(n) for n in zin.namelist()}
    doc = items.get("word/document.xml", b"").decode("utf-8")
    n = doc.count("<w:tbl>")
    if not n:
        return 0
    if full_width:
        doc = doc.replace('<w:tblW w:type="auto" w:w="0" />',
                          '<w:tblW w:type="pct" w:w="5000"/>')
        doc = doc.replace('<w:tblW w:type="auto" w:w="0"/>',
                          '<w:tblW w:type="pct" w:w="5000"/>')
    items["word/document.xml"] = doc.encode("utf-8")
    with zipfile.ZipFile(docx_path, "w", zipfile.ZIP_DEFLATED) as zout:
        for name, b in items.items():
            zout.writestr(name, b)
    return n


def add_page_setup(docx_path: str | Path, line_numbers: bool = False,
                   page: str = "letter") -> bool:
    """Give a built .docx an explicit page setup.

    Pandoc emits no ``<w:sectPr>`` at all, leaving page size and margins to
    whatever the reader's Word defaults to. Appending one section definition
    fixes the geometry.

    ``line_numbers`` is off by default: continuous numbering is what a journal
    asks for at submission, but it clutters a document being read or circulated,
    so it is opt-in rather than imposed.

    Returns True if the document was modified. OOXML fixes the child order of
    ``sectPr`` (pgSz, pgMar, lnNumType, cols, docGrid) and requires it to be the
    last child of ``body`` — both are respected here."""
    docx_path = Path(docx_path)
    w, h = (12240, 15840) if page == "letter" else (11906, 16838)  # DXA, A4
    ln = ('<w:lnNumType w:countBy="1" w:restart="continuous"/>'
          if line_numbers else "")
    sect = ('<w:sectPr>'
            f'<w:pgSz w:w="{w}" w:h="{h}"/>'
            '<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" '
            'w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>'
            f'{ln}<w:cols w:space="720"/><w:docGrid w:linePitch="360"/>'
            '</w:sectPr>')
    try:
        with zipfile.ZipFile(docx_path) as zin:
            items = {n: zin.read(n) for n in zin.namelist()}
        doc = items["word/document.xml"].decode("utf-8")
        if "<w:lnNumType" in doc:
            return False
        empty = re.search(r"<w:sectPr\s*/>", doc)
        if empty:
            # pandoc emits an empty self-closing section: replace it outright
            doc = doc.replace(empty.group(0), sect, 1)
        elif "<w:sectPr" in doc:
            # a populated section exists: only slot lnNumType in, before cols
            if not line_numbers or "<w:cols" not in doc:
                return False
            doc = doc.replace("<w:cols", ln + "<w:cols", 1)
        elif "</w:body>" in doc:
            doc = doc.replace("</w:body>", sect + "</w:body>", 1)
        else:
            return False
        items["word/document.xml"] = doc.encode("utf-8")
        with zipfile.ZipFile(docx_path, "w", zipfile.ZIP_DEFLATED) as zout:
            for n, b in items.items():
                zout.writestr(n, b)
        return True
    except Exception:
        return False


def make_reference_docx(out_docx: str | Path, font: str = "Times New Roman",
                        pt: float = 12.0) -> Path | None:
    """Build a pandoc ``--reference-doc`` with manuscript typography.

    Starts from pandoc's own default reference document and patches only the
    document defaults, so every style pandoc relies on stays intact. Returns
    None if pandoc is unavailable or its internal layout has changed — styling
    is a nicety, and must never be the reason a manuscript fails to build."""
    if shutil.which("pandoc") is None:
        return None
    out_docx = Path(out_docx)
    out_docx.parent.mkdir(parents=True, exist_ok=True)
    try:
        raw = subprocess.run(
            ["pandoc", "--print-default-data-file", "reference.docx"],
            check=True, capture_output=True).stdout
        tmp = out_docx.with_suffix(".base.docx")
        tmp.write_bytes(raw)

        half_pt = str(int(round(pt * 2)))
        with zipfile.ZipFile(tmp) as zin:
            items = {n: zin.read(n) for n in zin.namelist()}
        styles = items.get("word/styles.xml", b"").decode("utf-8")
        # Patch the document defaults only: every other style inherits from them.
        m = re.search(r"<w:rPrDefault>.*?</w:rPrDefault>", styles, re.S)
        if m:
            block = m.group(0)
            new = re.sub(r"<w:rFonts[^>]*/>",
                         f'<w:rFonts w:ascii="{font}" w:hAnsi="{font}" '
                         f'w:cs="{font}"/>', block, count=1)
            if "<w:rFonts" not in block:
                new = new.replace("<w:rPr>",
                                  f'<w:rPr><w:rFonts w:ascii="{font}" '
                                  f'w:hAnsi="{font}" w:cs="{font}"/>', 1)
            new = re.sub(r'<w:sz w:val="\d+"\s*/>', f'<w:sz w:val="{half_pt}"/>',
                         new)
            new = re.sub(r'<w:szCs w:val="\d+"\s*/>',
                         f'<w:szCs w:val="{half_pt}"/>', new)
            styles = styles.replace(block, new)

        # Replace pandoc's borderless `Table` style with the booktabs rules.
        # Done wholesale rather than by surgical edit: the replacement is a
        # complete, schema-ordered style, so the result does not depend on what
        # the stock style happened to contain.
        tbl = re.search(r'<w:style [^>]*w:styleId="Table"[^>]*>.*?</w:style>',
                        styles, re.S)
        if tbl:
            styles = styles.replace(tbl.group(0), _TABLE_STYLE)
        items["word/styles.xml"] = styles.encode("utf-8")

        with zipfile.ZipFile(out_docx, "w", zipfile.ZIP_DEFLATED) as zout:
            for n, b in items.items():
                zout.writestr(n, b)
        tmp.unlink(missing_ok=True)
        return out_docx
    except Exception:
        return None


def build_docx_pandoc(md_path: str | Path, out_docx: str | Path,
                      resource_dir: str | Path,
                      reference_docx: str | Path | None = None,
                      toc: bool = True) -> Path:
    """Convert Markdown to .docx with pandoc. Raises if pandoc is absent."""
    if shutil.which("pandoc") is None:
        raise RuntimeError("pandoc not found (try: apt-get install -y pandoc)")
    md_path, out_docx = Path(md_path), Path(out_docx)
    out_docx.parent.mkdir(parents=True, exist_ok=True)
    cmd = ["pandoc", str(md_path), "-o", str(out_docx),
           "--from", "markdown+pipe_tables+tex_math_dollars",
           "--resource-path", str(resource_dir), "--standalone"]
    if toc:
        cmd += ["--toc", "--toc-depth=3"]
    if reference_docx and Path(reference_docx).exists():
        cmd += ["--reference-doc", str(reference_docx)]
    subprocess.run(cmd, check=True, capture_output=True, text=True)
    return out_docx


def build_docx_fallback(md_path: str | Path, out_docx: str | Path,
                        resource_dir: str | Path) -> Path:
    """Minimal Markdown -> .docx via python-docx, used only when pandoc is absent.

    Handles headings, paragraphs, bullets, pipe tables and images. Inline
    emphasis markers are stripped rather than rendered: this build is for
    inspection, not for submission."""
    from docx import Document
    from docx.shared import Inches

    md_path, out_docx = Path(md_path), Path(out_docx)
    resource_dir = Path(resource_dir)
    doc = Document()
    lines = md_path.read_text(encoding="utf-8").splitlines()
    i, table_buf = 0, []

    def flush_table():
        nonlocal table_buf
        rows = [[c.strip() for c in r.strip().strip("|").split("|")]
                for r in table_buf
                if not re.fullmatch(r"\s*\|?[\s:|-]+\|?\s*", r)]
        table_buf = []
        if len(rows) < 2:
            return
        ncol = max(len(r) for r in rows)
        t = doc.add_table(rows=0, cols=ncol)
        t.style = "Table Grid"
        for r in rows:
            cells = t.add_row().cells
            for j, v in enumerate(r[:ncol]):
                cells[j].text = re.sub(r"[*_`]", "", v)

    while i < len(lines):
        ln = lines[i]
        if ln.strip().startswith("|"):
            table_buf.append(ln); i += 1; continue
        if table_buf:
            flush_table()
        m = IMG_RE.search(ln)
        if m:
            p = resource_dir / m.group(2)
            if p.exists():
                doc.add_picture(str(p), width=Inches(6.2))
                if m.group(1):
                    doc.add_paragraph(m.group(1), style="Caption")
            else:
                doc.add_paragraph(f"[MISSING IMAGE: {m.group(2)}]")
            i += 1; continue
        s = ln.strip()
        if s.startswith("#"):
            lvl = len(s) - len(s.lstrip("#"))
            doc.add_heading(re.sub(r"[*_`]", "", s.lstrip("# ").strip()),
                            level=min(lvl, 4))
        elif s.startswith(("- ", "* ")):
            doc.add_paragraph(re.sub(r"[*_`]", "", s[2:]), style="List Bullet")
        elif s.startswith("> "):
            doc.add_paragraph(re.sub(r"[*_`]", "", s[2:]), style="Intense Quote")
        elif s:
            doc.add_paragraph(re.sub(r"[*_`]", "", s))
        i += 1
    if table_buf:
        flush_table()
    out_docx.parent.mkdir(parents=True, exist_ok=True)
    doc.save(out_docx)
    return out_docx


def build_manuscript(paper_dir: str | Path, out_docx: str | Path,
                     title: str | None = None,
                     reference_docx: str | Path | None = None,
                     order: list[str] | None = None,
                     data_appendix: bool = True,
                     style: bool = True,
                     line_numbers: bool = False) -> dict:
    """Full pipeline: regenerate the data appendix, assemble, then convert.

    Returns the assembly report augmented with `engine` and `out_docx`, so the
    caller can see which converter ran — a fallback build must never be mistaken
    for a pandoc one."""
    paper_dir = Path(paper_dir)
    rep_tables = None
    if data_appendix:
        rep_tables = build_data_appendix(paper_dir / "figures",
                                         paper_dir / "09_appendix_data.md")
    if style and reference_docx is None:
        reference_docx = make_reference_docx(paper_dir / "_reference.docx")
    rep = assemble_markdown(paper_dir, paper_dir / "_manuscript.md", title, order)
    if rep_tables is not None:
        rep["n_tables"] = rep_tables["n_tables"]
        rep["tables"] = rep_tables["tables"]
    rep["reference_docx"] = str(reference_docx) if reference_docx else None
    try:
        build_docx_pandoc(rep["out_md"], out_docx, paper_dir, reference_docx)
        rep["engine"] = "pandoc"
    except Exception as e:
        rep["pandoc_error"] = str(e)
        build_docx_fallback(rep["out_md"], out_docx, paper_dir)
        rep["engine"] = "python-docx (DEGRADED formatting)"
    rep["content_types_fixed"] = repair_content_types(out_docx)
    rep["tables_polished"] = polish_tables(out_docx)
    rep["page_setup"] = add_page_setup(out_docx, line_numbers=line_numbers)
    rep["line_numbers"] = line_numbers
    rep["out_docx"] = Path(out_docx)
    return rep
